### ISSUE TITLE
add  program for  linear  search

### ISSUE THREAD

**Issue by Shubham56-droid** [Shubham56-droid/DataStruture-and-algroithms-program#1]
Add a program of linear search in  c++ or python or in java  languages don't forget to read rules in readme all valid PR will be accepted

**Comment by Shubham56-droid** [comment]
Try to write these program in java and python and c++

**Comment by MoKaif** [comment]
Can you assign me to write in java

**Comment by Shubham56-droid** [comment]
you can send pr directly no need to get assign and before sending pr pls star and follow me for successful acceptance of pr
