### ISSUE TITLE
CodeChef Problem : Solve it in  C or C++ 

### ISSUE THREAD

**Issue by Shubham56-droid** [Shubham56-droid/DataStruture-and-algroithms-program#232]
Problem Statement
Write a program that accepts sets of three numbers, and prints the second-maximum number among the three.

Input
First line contains the number of triples, N.
The next N lines which follow each have three space separated integers.
Output
For each of the N triples, output one new line which contains the second-maximum integer among the three.

Constraints
1 ≤ N ≤ 6
1 ≤ every integer ≤ 10000
The three integers in a single triplet are all distinct. That is, no two of them are equal.
Sample Input
3
1 2 3
10 15 5
100 999 500
Sample Output
2
10
500

**Comment by ankit6868** [comment]
plz assign me this

**Comment by ankit6868** [comment]
//contributed by ankit @Shubham56-droid solution
`#include <stdio.h>


void swap(int *xp, int *yp)
{
    int temp = *xp;
    *xp = *yp;
    *yp = temp;
}
 
// A function to implement bubble sort
void bubbleSort(int arr[]){
    int n = 3;
    int i, j;
    for (i = 0; i < n-1; i++)
        // Last i elements are already in place
        for (j = 0; j < n-i-1; j++)
            if (arr[j] > arr[j+1])
                swap(&arr[j], &arr[j+1]);
}
 

int main(){
    int t;
    scanf("%d",&t);
    int i;
    for ( i = 0; i < t; i++){
        int a[3];
        int j;
        for(j = 0; j<3;j++){
            scanf("%d",&a[j]);
        }
        bubbleSort(a);
        printf("%d\n",a[1]);
    }
    
}`

**Comment by hridyanshuk** [comment]
Hi, please assign this to me.

**Comment by Shubham56-droid** [comment]
no need to get assign just contribute it and pls star this repo and follow me

**Comment by ankit6868** [comment]
@Shubham56-droid  check pull request
