### ISSUE TITLE
Pls Do not contribute to this project any more

### ISSUE THREAD

**Issue by Shubham56-droid** [Shubham56-droid/DataStruture-and-algroithms-program#256]

**Comment by utkarsh1311** [comment]
If this project is excluded from Hacktoberfest 2021, then just remove the ```hacktoberfest```, ```hacktoberfest2021``` and ```hacktoberfest21``` labels from the repo and don't add them to the PRs submitted. No need to say that "Don't contribute to this project anymore".

**Comment by Shubham56-droid** [comment]
Bro it is not excluded but since one of my  repo is excluded i dont want this to be sxcluded

**Comment by utkarsh1311** [comment]
This will be excluded too. Hacktoberfest guidelines mention that any repo which merges PR for solving DSA problems or similar will not be considered valid for Hacktoberfest.
