### ISSUE TITLE
Remove Duplicate programs in the repository

### ISSUE THREAD

**Issue by Shubham56-droid** [Shubham56-droid/DataStruture-and-algroithms-program#285]

**Comment by POP1912** [comment]
May I take this issue?.

**Comment by Shubham56-droid** [comment]
sure

**Comment by Shubham56-droid** [comment]
pls submit your PR

**Comment by POP1912** [comment]
Do you want to remove all duplicate programs, even there is another approach to a problem, which has same algo?.

**Comment by Shubham56-droid** [comment]
dont remove if there is another approch which has same algo

**Comment by Shubham56-droid** [comment]
rest u can remove and send PR
