### ISSUE TITLE
Write a program to reverse an array or string in java

### ISSUE THREAD

**Issue by Shubham56-droid** [Shubham56-droid/DataStruture-and-algroithms-program#30]
save the program in the java folder as reverseArray.java

**Comment by sgaurav37533** [comment]
Please assign me this issue @Shubham56-droid

**Comment by Shubham56-droid** [comment]
no need to get assigned just put the pr and before read the rules in readme for repo

**Comment by Shubham56-droid** [comment]
star the repo and  follow me for more such questions
