### ISSUE TITLE
Write a prgram to swap two numbers in  c++

### ISSUE THREAD

**Issue by Shubham56-droid** [Shubham56-droid/DataStruture-and-algroithms-program#31]
put the file with c++ folder with swapnumber.cpp

**Comment by Nevilkumar** [comment]
Hii, I would like to work on this issue.

**Comment by Shubham56-droid** [comment]
bro just send pr no need to get assign and pls star this repo for more such questions and follow me.
Also check the rules in  readme file of this repo bro
