### ISSUE TITLE
Write a program for deletion in a linklist in c language

### ISSUE THREAD

**Issue by Shubham56-droid** [Shubham56-droid/DataStruture-and-algroithms-program#33]
put the file in  c folder as  LinklistDeletion

**Comment by ANIK-DATTA** [comment]
Assign me this task "Write a program for deletion in a linklist in c language "

**Comment by Shubham56-droid** [comment]
bro, there is no need to get assign and just put pr star this repo and follow me

**Comment by Shubham56-droid** [comment]
and send ur pr

**Comment by ANIK-DATTA** [comment]
please check my pr
thank you
