### ISSUE TITLE
Reverse  a Linked List in C++

### ISSUE THREAD

**Issue by dishagupta2413** [Shubham56-droid/DataStruture-and-algroithms-program#67]
I want to contribute to this issue. Please let me.

**Comment by dishagupta2413** [comment]
I want to contribute in it

**Comment by losermyluckwithyou007** [comment]
Sir , I will do this task please kindly assign me this issue

**Comment by Shubham56-droid** [comment]
bro no need to get assigned just send pr star this repo and follow me pls read , readme file befroe contribution

**Comment by tausiq2003** [comment]
can i contribute
