### ISSUE TITLE
add  a  program  for  insertion  sort

### ISSUE THREAD

**Issue by Shubham56-droid** [Shubham56-droid/DataStruture-and-algroithms-program#7]

**Comment by SidBthegr8** [comment]
hey, could you assign this to me? I wanna work on it.

**Comment by Shubham56-droid** [comment]
bro u can send the pr according to read me files rule do check it out all valid pr will be accepted

**Comment by Shubham56-droid** [comment]
Check the readme.md file of this repository

**Comment by SidBthegr8** [comment]
ok thanks!

**Comment by Shubham56-droid** [comment]
Try to write these program in java and python and c++
