### ISSUE TITLE
write a program to Segregate even and odd numbers

### ISSUE THREAD

**Issue by Shubham56-droid** [Shubham56-droid/DataStruture-and-algroithms-program#75]
write the progrm in  c++  and  python language

**Comment by Shubham56-droid** [comment]
before sending PR pls star this repo and follow me

**Comment by iamsandipanbera** [comment]
I can do in C++ . Can i make a PR?

**Comment by mukulgarg10** [comment]
Can you please assign this to me ? I can write in both languages.

**Comment by mephisto2975** [comment]
Unable to push. Is this issue closed as well??

**Comment by Shubham56-droid** [comment]
bro no need to get assigned just send pr star this repo and follow me pls read , readme file befroe contribution

**Comment by mephisto2975** [comment]
> no this issue is open

remote: Permission to Shubham56-droid/DataStruture-and-algroithms-program.git de
nied to mephisto2975.
fatal: unable to access 'https://github.com/Shubham56-droid/DataStruture-and-alg
roithms-program.git/': The requested URL returned error: 403

This is the error I'm getting. Can you help?
