### ISSUE TITLE
Sir , I have solved this task please kindly check my PR's

### ISSUE THREAD

**Issue by losermyluckwithyou007** [Shubham56-droid/DataStruture-and-algroithms-program#81]
Sir  ,I have solved this task please kindly check my PR's

_Originally posted by @losermyluckwithyou007 in https://github.com/Shubham56-droid/DataStruture-and-algroithms-program/issues/67#issuecomment-935340028_

**Comment by Shubham56-droid** [comment]
i have added ur pr bro
