### ISSUE TITLE
add  a  program  for sorting   queue without  extra  space

### ISSUE THREAD

**Issue by Shubham56-droid** [Shubham56-droid/DataStruture-and-algroithms-program#9]
Add your program to the repository it will be counted as your hacktober fest 2021 pull request.

**Comment by Shubham56-droid** [comment]
write the code and update in  the  repository

**Comment by Shubham56-droid** [comment]
Add all the DSA code of any topic in a particular folder as mention in the readme in any language all valid pull requests will be accepted. Don't forget to read the rules in the readme file as long as u did it correctly all pull requests will be merge.

**Comment by Shubham56-droid** [comment]
No need to ask to assignation anyone can contribute do as many contribution u could

**Comment by Shubham56-droid** [comment]
Try to write these program in java and python also

**Comment by khushboorathore10** [comment]
Added code for sorting queue without extra space please checkout #46
